export as1czt
CDIR=../common
EXE=cztmergescience
SOURCES=  main.cpp cztmergescience.cpp  $(CDIR)/level1handler.cpp $(CDIR)/l1evtdecode.cpp $(CDIR)/errorHandler.cpp $(CDIR)/utils.cpp $(CDIR)/cztstring.cpp $(CDIR)/gtiHandler.cpp $(CDIR)/cztHeaderParam.cpp 
include $(as1czt)/makefile.common 
