export as1czt
CDIR=../common

EXE=czthkextract_V2
SOURCES=  czthkextract_V2.cpp

//EXE=czthkextract
//SOURCES=  czthkextract.cpp  #$(CDIR)/level1handler.cpp $(CDIR)/l1evtdecode.cpp $(CDIR)/errorHandler.cpp $(CDIR)/utils.cpp $(CDIR)/cztstring.cpp $(CDIR)/gtiHandler.cpp $(CDIR)/cztHeaderParam.cpp 
include $(as1czt)/makefile.common 
