export as1czt
CDIR=../common

EXE=cztbindata

SOURCES= main.cpp cztbindata.cpp $(CDIR)/utils.cpp $(CDIR)/cztstring.cpp $(CDIR)/ExpMap.cpp $(CDIR)/coordinateTrasformation.cpp $(CDIR)/level1handler.cpp $(CDIR)/level2validation.cpp $(CDIR)/validations.cpp $(CDIR)/caldbHandler.cpp  $(CDIR)/errorHandler.cpp

include $(as1czt)/makefile.common

