export as1czt
CDIR=../common
EXE=cztexpmap

SOURCES= main.cpp cztexpmap.cpp $(CDIR)/detectorGeometry.cpp $(CDIR)/caldbHandler.cpp $(CDIR)/level2validation.cpp $(CDIR)/validations.cpp $(CDIR)/utils.cpp $(CDIR)/maskGeometry.cpp $(CDIR)/Exposure.cpp $(CDIR)/errorHandler.cpp $(CDIR)/badpixCALDB.cpp $(CDIR)/cztstring.cpp $(CDIR)/cztHeaderParam.cpp

include $(as1czt)/makefile.common

