export as1czt
CDIR=../common
EXE=cztpsfshadowgen

SOURCES= main.cpp $(CDIR)/utils.cpp $(CDIR)/cztstring.cpp $(CDIR)/Exposure.cpp $(CDIR)/coordinateTrasformation.cpp $(CDIR)/level1handler.cpp $(CDIR)/level2validation.cpp $(CDIR)/caldbHandler.cpp $(CDIR)/maskGeometry.cpp $(CDIR)/detectorGeometry.cpp $(CDIR)/validations.cpp cztpsfshadowgen.cpp $(CDIR)/errorHandler.cpp $(CDIR)/badpixCALDB.cpp $(CDIR)/Mvector.cpp $(CDIR)/mkfRegeneration.cpp $(CDIR)/cztHeaderParam.cpp
include $(as1czt)/makefile.common

