export as1czt
CDIR=../common

EXE=cztfindbadpix

SOURCES= main.cpp cztfindbadpix_v2.cpp $(CDIR)/utils.cpp $(CDIR)/cztstring.cpp $(CDIR)/ExpMap.cpp $(CDIR)/badpixCALDB.cpp $(CDIR)/coordinateTrasformation.cpp $(CDIR)/level1handler.cpp $(CDIR)/level2validation.cpp $(CDIR)/validations.cpp $(CDIR)/caldbHandler.cpp

include $(as1czt)/makefile.common

