export as1czt
CDIR=../common
EXE=cztsciheal
SOURCES=cztsciheal.cpp    $(CDIR)/level1handler.cpp $(CDIR)/l1evtdecode.cpp $(CDIR)/errorHandler.cpp $(CDIR)/utils.cpp $(CDIR)/cztstring.cpp $(CDIR)/gtiHandler.cpp $(CDIR)/cztHeaderParam.cpp 
include $(as1czt)/makefile.common 
