export as1czt
CDIR=../common
EXE=cztmkfgen
SOURCES= main.cpp cztmkfgen.cpp $(CDIR)/utils.cpp $(CDIR)/cztstring.cpp $(CDIR)/level1handler.cpp $(CDIR)/Mvector.cpp $(CDIR)/errorHandler.cpp $(CDIR)/mkfRegeneration.cpp $(CDIR)/cztHeaderParam.cpp
include $(as1czt)/makefile.common
