/* 
 * File:   cztbindatanew.h
 * Author: Tanul Gupta
 * Created on September 7, 2015, 4:11 PM
 */

#ifndef CZTBINDATANEW_H
#define	CZTBINDATANEW_H

#include<pil.h>
#include<pthread.h>
#include<iomanip>
#include <string>
#include"utils.h"
#include "glog/logging.h"
#include "badpixCALDB.h"
#include "cztstring.h"
#include "validations.h"
#include "coordinateTransformation.h"
#include "maskGeometry.h"
#include "detectorGeometry.h"
#include "caldbHandler.h"
#include "level2validation.h"
#include "level1handler.h"
#include "errorHandler.h"
#include "validations.h"

#define SPEC_EXTNAME "SPECTRUM"
#define LC_EXTNAME "LIGHTCURVE"

//Output type
#define SPEC 0
#define LC 1
#define SPECLC 2
//Coordinate type
#define CAMERA 0
#define CELESTIAL 1



using namespace std;


class cztbindata{
private:
    char modulename[NAMESIZE];
    char infile[PIL_LINESIZE];   //input event file
    //char compmaskfile[PIL_LINESIZE];
    char coordtype[PIL_LINESIZE];
    char aspectfileQ0[PIL_LINESIZE];
    char aspectfileQ1[PIL_LINESIZE];
    char aspectfileQ2[PIL_LINESIZE];
    char aspectfileQ3[PIL_LINESIZE];
    //char cameraGeomFile[PIL_LINESIZE];
    //char effectiveAreafile[PIL_LINESIZE]; 
    char pixelqualityfile[PIL_LINESIZE]; //badpix file generated by cztflagbadpix
    //char eboundsfile[PIL_LINESIZE];
    char outevtfile[PIL_LINESIZE];
    char outfile[PIL_LINESIZE];
    char outexparrayfile[PIL_LINESIZE];
    char livetimefile[PIL_LINESIZE];
    //    char timerange[PIL_LINESIZE];
    char energyrange[PIL_LINESIZE];
//    char gtifile[PIL_LINESIZE];  //required for gti binning
    float binsize;                 //required for uniform binning 
    char outputtype[25];          //lc/spec/both
    float theta1;
    float theta2;       
    char quadsToProcess[25];
    int nbins;                //will hold number of bins
    int badpixThreshold;      //badpix Threshold
    int outtypeflag;          //0:Spectrum 1:Light Curve 2:Both
    int coordflag;            //coordinate flag type
    float ra,dec;
    int clobber;
    int history;
    int debug;
	int maskWeight;
    
    //to store caldb file paths
    string compMaskFilepath;
    
    
    
public:
    cztbindata();
    ~cztbindata();
    int read(int argc,char **argv);
    int read(char *infile, char* coordtype, vector <string> aspectFileNames, char *quadsToProcess, char *pixelqualityfile,
    char* outputtype,  char *energyrange, char* outfile,char *outevtfile, char* outexparrayfile, char *livetimefile, int badpixThreshold=1, float binsize=1.0, float theta1=0.0,
            float theta2=0.0, int clobber=YES, int history=YES, int debug=YES,int maskWeight=YES);
    void display();
    void clear();
    
    /**
    * Function to produce light curve or spectrum
    * @param par
    * @return 
    */
    int cztbindataProcess();

    /**
    * Function to generate history for the module, to be written to the output file
    * @param vhistory
    * @return 
    */
    int getHistory(vector<string> &vhistory);
    
};

#endif /*CZTBINDATANEW_H*/


